# Generated by Django 2.1 on 2019-08-02 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invi_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='lecturebook',
            table='lectureBook',
        ),
        migrations.AlterModelTable(
            name='lecturecategory',
            table='lectureCategory',
        ),
        migrations.AlterModelTable(
            name='lecturefeature',
            table='lectureFeature',
        ),
        migrations.AlterModelTable(
            name='lecturepackage',
            table='lecturePackage',
        ),
        migrations.AlterModelTable(
            name='lectureteacher',
            table='lectureTeacher',
        ),
        migrations.AlterModelTable(
            name='teacherfeature',
            table='teacherFeature',
        ),
        migrations.AlterModelTable(
            name='userfeature',
            table='userFeature',
        ),
        migrations.AlterModelTable(
            name='userlecture',
            table='userLecture',
        ),
    ]
