# Generated by Django 2.1.4 on 2019-08-03 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invi_app', '0003_auto_20190804_0350'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='feature',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lecture',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lecturebook',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lecturecategory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lecturefeature',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lecturepackage',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='lectureteacher',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='package',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='teacherfeature',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userfeature',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userlecture',
            options={'managed': False},
        ),
    ]
